#!/bin/bash

time="$(TZ=IST date)"
current_time=$time
echo $current_time



## Job Sequencing
echo "*************Cloning oep-e2e-konvoy repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone https://github.com/mayadata-io/oep-e2e-konvoy.git'

cd oep-e2e-konvoy
echo "***Applying e2e-crd***********"
kubectl apply -f utils/e2e-crd.yml

bash utils/e2e-cr jobname:cluster-create jobphase:Waiting
bash utils/e2e-cr jobname:cluster-create jobphase:Running 
bash utils/e2e-cr jobname:litmus-deps-setup jobphase:Waiting

echo "***Checking the cluster is Engaged or not***"

state="sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'ls | grep oep-e2e-konvoy'"
cluster_state=$(eval $state)

while [ "${cluster_state}" == "oep-e2e-konvoy" ]; do
  echo "***Cluster is Engaged***"
  wait=1
  cluster_state=$(eval $state)
  sleep 30
done

if [ "$wait" == "1" ]; then
sleep 120
fi

echo "*************************Checking the Cluster's Health********************"

# ssh into the deployer machine and check number of ready nodes
echo "***************Checking for the number of nodes in ready state***************"
ready_nodes=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes | grep Ready | wc -l)

if [ "$ready_nodes" -eq 6 ]; then
echo "Number of nodes in ready state is $ready_nodes"
echo "******Cluster is in Healthy state******"

echo "*************Dumping cluster state*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get pod --all-namespaces

bash utils/e2e-cr jobname:create-apikey-check jobphase:Completed
else
echo "All nodes are not ready"
echo "*******Cluster is in Unhealthy state*******"
    bash utils/e2e-cr jobname:create-apikey-check jobphase:Completed
exit;
fi
