#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"' '"'$RELEASE_TAG'"'
}

node() {

export KUBECONFIG=~/.kube/config_c2

job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
case_id=4E0O

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash utils/e2e-cr-new jobname:jiva-replica-scaleup jobphase:Waiting
bash utils/e2e-cr-new jobname:jiva-replica-scaleup jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

###########Deploying Busybox Application

################
# LitmusBook 1 #
################

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specifc value                                    |
  --------------------------------------------------------------------------------------------------------------------------|
 | Litmus job label  | label  | app: busybox-litmus                 | app: deploy-jiva-busybox-rep-scaleup                  |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-provision-jiva-replica-scaleup  |
 | appLabel          | env    | app=busybox-sts                     | app=busybox-jiva-replica                              |
 | deploy type       | env    | statefulset                         | deployment                                            |
 | pvcName           | env    | openebs-busybox                     | busybox-jiva-replica-scaleup                          | 
 | storage clas      | env    | openebs-cstor-sparse                | openebs-jiva-default                               |
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                                  |
  ---------------------------------------------------------------------------------------------------------------------------
EOF

test_name=$(bash utils/generate_test_name testcase=busybox-provision-jiva-replica-scaleup metadata="")
echo $test_name

cd e2e-tests
echo "Running the litmus test for Busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml deploy_busybox_jiva_replica_scale.yml

sed -i -e 's/app: busybox-litmus/app: deploy-jiva-busybox-rep-scaleup/g' \
-e 's/generateName: litmus-busybox-deploy/generateName: busybox-provision-jiva-replica-scaleup/g' \
-e 's/app=busybox-sts/app=busybox-jiva-replica/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-busybox/value: busybox-jiva-replica-scaleup/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' \
-e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' deploy_busybox_jiva_replica_scale.yml

cat deploy_busybox_jiva_replica_scale.yml

bash ../utils/litmus_job_runner label='app:deploy-jiva-busybox-rep-scaleup' deploy_busybox_jiva_replica_scale.yml
cd ..
bash utils/dump_cluster_state;
bash utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##Running Busybox loadgen 

#################
# LitmusBook 2 #
#################

run_id="jiva-rep-scaleup";test_name=$(bash utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_jiva_rep_scaleup.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                             | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-app-rep-scaleup       |
 | appLabel          | env    | app=busybox-sts                     | app=busybox-jiva-replica                         | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/app=busybox-sts/app=busybox-jiva-replica/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-app-rep-scaleup/g' busybox_loadgen_jiva_rep_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_jiva_rep_scaleup.yml

cat busybox_loadgen_jiva_rep_scaleup.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='liveness:busybox-liveness-app-rep-scaleup' job=busybox_loadgen_jiva_rep_scaleup.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
# Update the e2e event for the job.
bash utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##Scaling up the Jiva replicas 

#################
# LitmusBook 3 #
#################

test_name=$(bash utils/generate_test_name testcase=scaleup-jiva-replica metadata="")
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/functional/scale_jiva_replica/run_litmus_test.yml busybox_scale_jiva_rep.yml

 # Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-percona-ns                      | jiva-replica-scaleup                             |  
 | appPVC            | env    | percona-mysql-claim                 | busybox-jiva-replica-scaleup                     |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app-percona-ns/jiva-replica-scaleup/g' \
-e 's/percona-mysql-claim/busybox-jiva-replica-scaleup/g'  busybox_scale_jiva_rep.yml

cat  busybox_scale_jiva_rep.yml
 # Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='app:scaleup-jiva-replica-litmus' job=busybox_scale_jiva_rep.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
bash utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

#Deprovisioning Busybox-loadgen

################
# LitmusBook 4 #
################

run_id="deprovision-jiva-rep-scaleup";test_name=$(bash utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_jiva_rep_scaleup.yml

# Update the environmental variables in litmus job spec.

: << EOF
  --------------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                                          |
  --------------------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                                        | 
 | appLabel          | env    | app=busybox-sts                     | app=busybox-jiva-replica                                    |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-jiva-replica-scaleup |
 | action            | env    | provision                           | deprovision                                                 | 
  ---------------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/app=busybox-sts/app=busybox-jiva-replica/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-replica-scaleup/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-replica-scaleup/g' busybox_loadgen_deprovision_jiva_rep_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_jiva_rep_scaleup.yml

cat busybox_loadgen_deprovision_jiva_rep_scaleup.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-replica-scaleup' job=busybox_loadgen_deprovision_jiva_rep_scaleup.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
bash utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)


if [ "$rc_val" != "0" ]; then
exit 1;
fi

###########-Deprovisioning busybox Application

################
# LitmusBook 5 #
################
test_name=$(bash utils/generate_test_name testcase=busybox-deprovision-jiva-replica-scaleup metadata="")
echo $test_name

cd e2e-tests
cp apps/busybox/deployers/run_litmus_test.yml deprovision_busybox_jiva_replica.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-replica-scaleup/g' \
-e 's/app: busybox-litmus/app: deprovision-jiva-busybox-rep-scaleup/g' \
-e 's/app=busybox-sts/app=busybox-jiva-replica/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' \
-e 's/value: openebs-busybox/value: busybox-jiva-replica-scaleup/g' \
-e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/value: provision/value: deprovision/g' deprovision_busybox_jiva_replica.yml

cat deprovision_busybox_jiva_replica.yml

bash ../utils/litmus_job_runner label='app:deprovision-jiva-busybox-rep-scaleup' job=deprovision_busybox_jiva_replica.yml
cd ..
bash utils/dump_cluster_state;
bash utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
return_count=$?
current_time=$(eval $time)

if [ "$return_count" != "0" ]; then
bash utils/e2e-cr-new jobname:jiva-replica-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash utils/e2e-cr-new jobname:jiva-replica-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$return_count" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
