## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - DIRECTOR-INSTALL-AND-UPGRADE
  - FUNCTIONAL-TESTING-WITH-REST
  - CLUSTER-TEAR-DOWN ## This stage is fixed and should not be changed

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/check-cluster-state/cluster-setup.sh
    - ./stages/cluster-setup/check-cluster-state/cluster-setup.sh
  artifacts:
    paths:
      - .cluster-info/

## Deploy Director On-Prem
director-deploy:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-INSTALL-AND-UPGRADE
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install-and-upgrade/dop-deploy.sh
    - ./stages/director-install-and-upgrade/dop-deploy.sh

## Director components health check jobs
director-health-check:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-INSTALL-AND-UPGRADE
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install-and-upgrade/components-health-check.sh
    - ./stages/director-install-and-upgrade/components-health-check.sh

## Create user's apikey
create-apikey-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh

## Cluster connect check
trrc01-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh

## Client component check
client-components-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - director-deploy
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh

## E2E metrics stage
e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/e2e-metrics.sh
    - ./stages/cluster-tear-down/e2e-metrics.sh

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/cluster-cleanup.sh
    - ./stages/cluster-tear-down/cluster-cleanup.sh
