## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - DIRECTOR-INSTALL-AND-UPGRADE
  - FUNCTIONAL-TESTING-WITH-REST
  - CLUSTER-TEAR-DOWN ## This stage is fixed and should not be changed

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/check-cluster-state/cluster-setup
    - ./stages/cluster-setup/check-cluster-state/cluster-setup

## Dependencies Setup
litmus-deps-setup:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-INSTALL-AND-UPGRADE
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install-and-upgrade/litmus-dependencies/litmus-deps-setup
    - ./stages/director-install-and-upgrade/litmus-dependencies/litmus-deps-setup

## Deploy Director On-Prem
director-deploy:
  image: harshshekhar15/gitlab-job:v2
  stage: DIRECTOR-INSTALL-AND-UPGRADE
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install-and-upgrade/dop-deploy
    - ./stages/director-install-and-upgrade/dop-deploy

# # director health check jobs
# maya-io-server-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/director-health-check/maya-io-server-check
#     - ./stages/director-install-and-upgrade/director-health-check/maya-io-server-check
#   artifacts:
#     paths:
#       - .kube/

# maya-ui-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/maya-ui-check
#     - ./stages/director-install-and-upgrade/maya-ui-check
#   artifacts:
#     paths:
#       - .kube/

# od-elasticsearch-logging-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/od-elasticsearch-logging-check
#     - ./stages/director-install-and-upgrade/od-elasticsearch-logging-check
#   artifacts:
#     paths:
#       - .kube/

# od-kibana-logging-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/od-kibana-logging-check
#     - ./stages/director-install-and-upgrade/od-kibana-logging-check
#   artifacts:
#     paths:
#       - .kube/

# table-manager-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/table-manager-check
#     - ./stages/director-install-and-upgrade/table-manager-check
#   artifacts:
#     paths:
#       - .kube/

# chat-server-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/chat-server-check
#     - ./stages/director-install-and-upgrade/chat-server-check
#   artifacts:
#     paths:
#       - .kube/

# cloud-agent-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/cloud-agent-check
#     - ./stages/director-install-and-upgrade/cloud-agent-check
#   artifacts:
#     paths:
#       - .kube/

# mysql-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/mysql-check
#     - ./stages/director-install-and-upgrade/mysql-check
#   artifacts:
#     paths:
#       - .kube/

# maya-grafana-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/maya-grafana-check
#     - ./stages/director-install-and-upgrade/maya-grafana-check
#   artifacts:
#     paths:
#       - .kube/

# memcached-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/memcached-check
#     - ./stages/director-install-and-upgrade/memcached-check
#   artifacts:
#     paths:
#       - .kube/

# ## cortex infrastructure components jobs
# alertstore-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/alertstore-check
#     - ./stages/director-install-and-upgrade/alertstore-check
#   artifacts:
#     paths:
#       - .kube/

# alertstore-tablemanager-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/alertstore-tablemanager-check
#     - ./stages/director-install-and-upgrade/alertstore-tablemanager-check
#   artifacts:
#     paths:
#       - .kube/

# alertmanager-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/alertmanager-check
#     - ./stages/director-install-and-upgrade/alertmanager-check
#   artifacts:
#     paths:
#       - .kube/

# cassandra-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/cassandra-check
#     - ./stages/director-install-and-upgrade/cassandra-check
#   artifacts:
#     paths:
#       - .kube/

# distributor-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/distributor-check
#     - ./stages/director-install-and-upgrade/distributor-check
#   artifacts:
#     paths:
#       - .kube/

# ingestor-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/ingestor-check
#     - ./stages/director-install-and-upgrade/ingestor-check
#   artifacts:
#     paths:
#       - .kube/

# querier-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/querier-check
#     - ./stages/director-install-and-upgrade/querier-check
#   artifacts:
#     paths:
#       - .kube/

# ruler-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/ruler-check
#     - ./stages/director-install-and-upgrade/ruler-check
#   artifacts:
#     paths:
#       - .kube/

# configs-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/configs-check
#     - ./stages/director-install-and-upgrade/configs-check
#   artifacts:
#     paths:
#       - .kube/

# configs-db-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/configs-db-check
#     - ./stages/director-install-and-upgrade/configs-db-check
#   artifacts:
#     paths:
#       - .kube/

# ingress-nginx-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-INSTALL-AND-UPGRADE
#   dependencies:
#     - director-deploy
#   script:
#     - chmod 755 ./stages/director-install-and-upgrade/ingress-nginx-check
#     - ./stages/director-install-and-upgrade/ingress-nginx-check
#   artifacts:
#     paths:
#       - .kube/

## E2E metrics stage
e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/e2e-metrics
    - ./stages/cluster-tear-down/e2e-metrics

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/cluster-cleanup
    - ./stages/cluster-tear-down/cluster-cleanup
