## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - DOP-SETUP
  - E2E-METRICS ## This stage is fixed and should not be changed
  - CLUSTER-CLEANUP

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster-setup
    - ./stages/cluster-setup/cluster-setup

## Deploy Director On-Prem
director-deploy:
  image: harshshekhar15/gitlab-job:v2
  stage: DOP-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-deploy/dop-deploy
    - ./stages/director-deploy/dop-deploy

## E2E metrics stage
e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v1
  stage: E2E-METRICS
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/e2e-metrics/e2e-metrics
    - ./stages/e2e-metrics/e2e-metrics

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cluster-cleanup
    - ./stages/cluster-cleanup/cluster-cleanup
