## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - DIRECTOR-INSTALL-AND-UPGRADE
  - FUNCTIONAL-TESTING-WITH-REST
  - OPENEBS-INSTALL
  - TEAMING-CHECK
  - TOPOLOGY-CHECK
  - DIRECTOR-GUI
  - CLUSTER-TEAR-DOWN ## This stage is fixed and should not be changed

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/check-cluster-state/cluster-setup.sh
    - ./stages/cluster-setup/check-cluster-state/cluster-setup.sh

## Deploy Director On-Prem
TCID-DIR-INSTALL-ON-LOCAL-HP:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-INSTALL-AND-UPGRADE
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install-and-upgrade/dop-deploy.sh
    - ./stages/director-install-and-upgrade/dop-deploy.sh

## Create user's apikey
create-apikey-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh

## Cluster connect check
trrc01-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh

## Client component check
client-components-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh

## Self cluster connect check
director-self-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh

## OpenEBS install
tcid-iuoi02-openebs-install:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/tcid-iuoi02-openebs-install.sh
    - ./stages/openebs-install/tcid-iuoi02-openebs-install.sh

TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE.sh
    - ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE.sh

# ## Director metrics check
metrics-check:
  image: harshshekhar15/gitlab-job:v3
  stage: FUNCTIONAL-TESTING-WITH-REST
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh
    - ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh

## Teaming checks
triv01-teaming-invite-check:
  image: harshshekhar15/gitlab-job:v3
  stage: TEAMING-CHECK
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh

trrc02-teaming-change-role-check:
  image: harshshekhar15/gitlab-job:v3
  stage: TEAMING-CHECK
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh

trrc03-teaming-change-role-negative-check:
  image: harshshekhar15/gitlab-job:v3
  stage: TEAMING-CHECK
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh

## Topology check
topology-check:
  image: harshshekhar15/gitlab-job:v3
  stage: TOPOLOGY-CHECK
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/topology-check/topology-check.sh
    - ./stages/functional-testing-with-rest/topology-check/topology-check.sh

## Selenium Grid Spin up
selenium-grid-deploy:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-gui/create-grid.sh
    - ./stages/director-gui/create-grid.sh

## Selenium tests
tcid-gaau01-gui-auth:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gaau01-gui-auth.sh
    - ./stages/director-gui/tcid-gaau01-gui-auth.sh

tcid-gacc01-gui-cluster:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gacc01-gui-cluster.sh
    - ./stages/director-gui/tcid-gacc01-gui-cluster.sh

tcid-gada01-gui-dashboard-home:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gada01-gui-dashboard-home.sh
    - ./stages/director-gui/tcid-gada01-gui-dashboard-home.sh

tcid-gato01-gui-dashboard-topology:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gato01-gui-dashboard-topology.sh
    - ./stages/director-gui/tcid-gato01-gui-dashboard-topology.sh

gui-dashboard:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-dashboard.sh
    - ./stages/director-gui/gui-dashboard.sh

tcid-gaal01-gui-dashboard-alerts:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gaal01-gui-dashboard-alerts.sh
    - ./stages/director-gui/tcid-gaal01-gui-dashboard-alerts.sh

tcid-galo01-gui-dashboard-logs:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-galo01-gui-dashboard-logs.sh
    - ./stages/director-gui/tcid-galo01-gui-dashboard-logs.sh

tcid-gada02-gui-dashboard-overview:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gada02-gui-dashboard-overview.sh
    - ./stages/director-gui/tcid-gada02-gui-dashboard-overview.sh

## Selenium Grid Clean up
selenium-grid-cleanup:
  image: harshshekhar15/gitlab-job:v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/cluster-tear-down/delete-grid.sh
    - ./stages/cluster-tear-down/delete-grid.sh

## E2E metrics stage
e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/e2e-metrics.sh
    - ./stages/cluster-tear-down/e2e-metrics.sh

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/cluster-cleanup.sh
    - ./stages/cluster-tear-down/cluster-cleanup.sh

cluster2-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c2-cleanup.sh
    - ./stages/cluster-tear-down/c2-cleanup.sh
