## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - INFRA-SETUP
  - CLUSTER-CONNECT
  - OPENEBS-SETUP
  - OPENEBS-FUNCTIONAL
  - OPENEBS-CHAOS
  # - DIRECTOR-FUNCTIONAL
  - DIRECTOR-GUI
  - CLUSTER-TEAR-DOWN ## This stage is fixed and should not be changed

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster1-setup.sh
    - ./stages/cluster-setup/cluster1-setup.sh

cluster2-create:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster2-setup
    - ./stages/cluster-setup/cluster2-setup

cluster3-create:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster3-setup
    - ./stages/cluster-setup/cluster3-setup

## Deploy Director On-Prem
TCID-DIR-INSTALL-ON-LOCAL-HP:
  image: mayadataio/tools:gitlab-job-v5
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP
    - ./stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP

## Create user's apikey
create-apikey-check:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh

## Cluster connect check
trrc01-cluster-connect-check:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh

## Client component check
client-components-check:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh

## Self cluster connect check
director-self-cluster-connect-check:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh

## Cluster3 connect check
cluster3-connect:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster3-connect
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster3-connect

client3-components-check:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client3-components-check
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client3-components-check

## OpenEBS install
TCID-DIR-OP-INSTALL-OPENEBS:
  image: mayadataio/tools:gitlab-job-v5
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS
    - ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS

TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE:
  image: mayadataio/tools:gitlab-job-v5
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE
    - ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE

TCID-OPENEBS-POLICIES-CREATE:
  image: mayadataio/tools:gitlab-job-v5
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/openebs-storage-policies
    - ./stages/openebs-install/openebs-storage-policies

## OpenEBS Functional Tests

.func_test_template:
  image: mayadataio/tools:gitlab-job-v5
  stage: OPENEBS-FUNCTIONAL
  dependencies:
    - TCID-DIR-OP-INSTALL-OPENEBS

TCID-JIVA-APP-TARGET-AFFINITY:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity
    - ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity

TCID-JIVA-SNAPSHOT-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-snapshot/jiva-snapshot
    - ./stages/functional/Jiva-snapshot/jiva-snapshot

TCID-JIVA-VOLUME-SCALEUP:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup
    - ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup

TCID-CSTOR-SNAPSHOT-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot
    - ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot

TCID-CSTOR-CLONE-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone
    - ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone

TCID-CSTOR-VOLUME-EXT4-RESIZE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize
    - ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize

TCID-CSTOR-VOLUME-XFS-RESIZE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs
    - ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs

TCID-LOCALPV-RANDOM-DEVICE-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/local-pv-device/local-pv-device
    - ./stages/functional/local-pv-device/local-pv-device

TCID-LOCALPV-HOSTPATH-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/local-pv-hostpath/local-pv-hostpath
    - ./stages/functional/local-pv-hostpath/local-pv-hostpath

# OpenEBS CHAOS Tests JOBS

.chaos_test_template:
  image: mayadataio/tools:gitlab-job-v5
  stage: OPENEBS-CHAOS
  dependencies:
    - TCID-DIR-OP-INSTALL-OPENEBS

TCID-JIVA-BUSYBOX-KILL:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-App-kill/jiva-app-kill
    - ./stages/chaos/Jiva-App-kill/jiva-app-kill

TCID-JIVA-MULTIPLE-REPLICAS-FAILURE:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-revision-counter/jiva-revision-counter
    - ./stages/chaos/Jiva-revision-counter/jiva-revision-counter

TCID-JIVA-REPLICA-NETWORK-DELAY:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay
    - ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay

TCID-JIVA-CONTROLLER-KILL:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill
    - ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill

TCID-JIVA-CONTROLLER-NETWORK-DELAY:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay
    - ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay

TCID-JIVA-REPLICA-NODE-AFFINITY:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity
    - ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity

TCID-CSTOR-BUSYBOX-APP-KILL:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/cstor-App-pod-kill/app-kill
    - ./stages/chaos/cstor-App-pod-kill/app-kill

TCID-CSTOR-TARGET-KILL:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/cstor-Target-kill/target-kill
    - ./stages/chaos/cstor-Target-kill/target-kill

# ## Director metrics check
# metrics-check:
#   image: mayadataio/tools:gitlab-job-v5
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh
#     - ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh

## Teaming checks
# TCID-DIR-TEAMING-USER-INVITE:
#   image: mayadataio/tools:gitlab-job-v5
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh
#     - ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh

# TCID-DIR-TEAMING-USER-ROLE-UPDATE:
#   image: mayadataio/tools:gitlab-job-v5
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh
#     - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh

# TCID-DIR-TEAMING-USER-ROLE-UPDATE-NEGATIVE:
#   image: mayadataio/tools:gitlab-job-v5
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh
#     - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh

## Topology check
# topology-check:
#   image: mayadataio/tools:gitlab-job-v5
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/topology-check/topology-check.sh
#     - ./stages/functional-testing-with-rest/topology-check/topology-check.sh

## GUI Checks
.gui_test_template:
  when: always
  image: mayadataio/tools:gitlab-job-v6
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/run-gui-tests
    - ./stages/director-gui/run-gui-tests
  artifacts:
    when: always
    paths:
      - /builds/oep/oep-e2e-konvoy/gui-automation/results

TCID-GUI-AUTH:
  extends: .gui_test_template
  variables:
    GROUP: auth
    THREADS: 10

TCID-DIR-AUTH-LOCAL-ADMIN:
  extends: .gui_test_template
  variables:
    GROUP: localAdminAuth
    THREADS: 10

TCID-DIR-AUTH-LOCAL-USER:
  extends: .gui_test_template
  variables:
    GROUP: localUserAuth
    THREADS: 10

TCID-DIR-AUTH-LOCAL-PERF:
  extends: .gui_test_template
  variables:
    GROUP: localPerfAuth
    THREADS: 10

TCID-GUI-CLUSTER:
  extends: .gui_test_template
  variables:
    GROUP: cluster
    THREADS: 10

TCID-GUI-DASHBOARD:
  extends: .gui_test_template
  variables:
    GROUP: dashboard
    THREADS: 10

TCID-GUI-PROFILE:
  extends: .gui_test_template
  variables:
    GROUP: profile
    THREADS: 10

TCID-DIR-TEAMING-USER-INVITE:
  extends: .gui_test_template
  variables:
    GROUP: teamingUserInvite
    THREADS: 10

TCID-DIR-TEAMING-USER-ROLE-UPDATE:
  extends: .gui_test_template
  variables:
    GROUP: teamingRoleUpdate
    THREADS: 10

TCID-DIR-TEAMING-USER-ROLE-UPDATE-NEGATIVE:
  extends: .gui_test_template
  variables:
    GROUP: teamingRoleUpdateNegative
    THREADS: 10

TCID-DIR-GUI-OPENEBS-COMPONENTS-VERSION:
  extends: .gui_test_template
  variables:
    GROUP: openebs
    THREADS: 10

## Selenium Grid Clean up
selenium-grid-cleanup:
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/cluster-tear-down/selenium-grid-cleanup
    - ./stages/cluster-tear-down/selenium-grid-cleanup

## E2E metrics stage
e2e-metrics:
  when: always
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/e2e-metrics.sh
    - ./stages/cluster-tear-down/e2e-metrics.sh

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c1-cleanup.sh
    - ./stages/cluster-tear-down/c1-cleanup.sh

cluster2-cleanup:
  when: always
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c2-cleanup.sh
    - ./stages/cluster-tear-down/c2-cleanup.sh

cluster3-cleanup:
  when: always
  image: mayadataio/tools:gitlab-job-v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c3-cleanup.sh
    - ./stages/cluster-tear-down/c3-cleanup.sh
