## Define the stages & order of execution
stages:
  - CLUSTER-SETUP
  - DIRECTOR-INSTALL
  - CLUSTER-CONNECT
  - OPENEBS-SETUP
  - OPENEBS-FUNCTIONAL
  - OPENEBS-CHAOS
  - DIRECTOR-FUNCTIONAL
  # - METRICS-CHECK
  # - TEAMING-CHECK
  # - TOPOLOGY-CHECK
  - DIRECTOR-GUI
  - CLUSTER-TEAR-DOWN ## This stage is fixed and should not be changed

## Setup kubernetes cluster using Konvoy
cluster-create:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster1-setup.sh
    - ./stages/cluster-setup/cluster1-setup.sh

cluster2-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster2-setup
    - ./stages/cluster-setup/cluster2-setup

cluster3-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/cluster3-setup
    - ./stages/cluster-setup/cluster3-setup

## Deploy Director On-Prem
TCID-DIR-INSTALL-ON-LOCAL-HP:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-INSTALL
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP
    - ./stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP

## Create user's apikey
create-apikey-check:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/create-apikey-check.sh

## Cluster connect check
trrc01-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster-connect-check.sh

## Client component check
client-components-check:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client-components-check.sh

## Self cluster connect check
director-self-cluster-connect-check:
  image: harshshekhar15/gitlab-job:v3
  stage: CLUSTER-CONNECT
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh
    - ./stages/functional-testing-with-rest/cluster-connect-checks/self-connect-cluster-check.sh

## Cluster3 connect check
cluster3-connect:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/cluster3-connect
    - ./stages/functional-testing-with-rest/cluster-connect-checks/cluster3-connect

client3-components-check:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/functional-testing-with-rest/cluster-connect-checks/client3-components-check
    - ./stages/functional-testing-with-rest/cluster-connect-checks/client3-components-check

## OpenEBS install
TCID-DIR-OP-INSTALL-OPENEBS:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS
    - ./stages/openebs-install/TCID-DIR-OP-INSTALL-OPENEBS

TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE
    - ./stages/openebs-install/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE

OPENEBS-STORAGE-POLICIES:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/openebs-install/openebs-storage-policies
    - ./stages/openebs-install/openebs-storage-policies

## OpenEBS Functional Tests

.func_test_template:
  image: harshshekhar15/gitlab-job:v5
  stage: OPENEBS-FUNCTIONAL
  when: always
  dependencies:
    - TCID-DIR-OP-INSTALL-OPENEBS

Jiva-App-Target-Affinity:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity
    - ./stages/functional/Jiva-App-Target-Affinity/app-target-affinity

Jiva-Snapshot:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-snapshot/jiva-snapshot
    - ./stages/functional/Jiva-snapshot/jiva-snapshot

Jiva-Volume-Scaleup:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup
    - ./stages/functional/Jiva-Volume-Scaleup/jiva-vol-scaleup

cStor-csi-volume-snapshot:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot
    - ./stages/functional/cstor-csi-volume-snapshot/csi-cstor-snapshot

cStor-csi-volume-clone:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone
    - ./stages/functional/cstor-csi-volume-clone/csi-cstor-clone

cStor-ext4-volume-resize:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize
    - ./stages/functional/cstor-ext4-volume-resize/csi-volume-resize

cStor-xfs-volume-resize:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs
    - ./stages/functional/cstor-xfs-volume-resize/csi-volume-resize-xfs

LocalPV-device:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/local-pv-device/local-pv-device
    - ./stages/functional/local-pv-device/local-pv-device

LocalPV-hostpath:
  extends: .func_test_template
  script:
    - chmod 755 ./stages/functional/local-pv-hostpath/local-pv-hostpath
    - ./stages/functional/local-pv-hostpath/local-pv-hostpath

# OpenEBS CHAOS Tests JOBS

.chaos_test_template:
  image: harshshekhar15/gitlab-job:v2
  stage: OPENEBS-CHAOS
  when: always
  dependencies:
    - TCID-DIR-OP-INSTALL-OPENEBS

Jiva-App-Kill:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-App-kill/jiva-app-kill
    - ./stages/chaos/Jiva-App-kill/jiva-app-kill

Jiva-Revision-Counter:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-revision-counter/jiva-revision-counter
    - ./stages/chaos/Jiva-revision-counter/jiva-revision-counter

Jiva-Replica-Network-Delay:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay
    - ./stages/chaos/Jiva-Replica-Network-Delay/jiva-replica-network-delay

Jiva-Controller-Kill:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill
    - ./stages/chaos/Jiva-Controller-kill/jiva-controller-kill

Jiva-Controller-Network-Delay:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay
    - ./stages/chaos/Jiva-Controller-Network-Delay/ctrl-network-delay

Jiva-Replica-Node-Affinity:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity
    - ./stages/chaos/Jiva-Replica-Node-Affinity/rep-node-affinity

cStor-App-kill:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/cstor-App-pod-kill/app-kill
    - ./stages/chaos/cstor-App-pod-kill/app-kill

cStor-Target-kill:
  extends: .chaos_test_template
  script:
    - chmod 755 ./stages/chaos/cstor-Target-kill/target-kill
    - ./stages/chaos/cstor-Target-kill/target-kill

# ## Director metrics check
# metrics-check:
#   image: harshshekhar15/gitlab-job:v3
#   stage: DIRECTOR-FUNCTIONAL
#   dependencies:
#     - client-components-check
#   script:
#     - chmod 755 ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh
#     - ./stages/functional-testing-with-rest/metrics-check/metrics-check.sh

## Teaming checks
triv01-teaming-invite-check:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-FUNCTIONAL
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-invite-check.sh

trrc02-teaming-change-role-check:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-FUNCTIONAL
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-check.sh

trrc03-teaming-change-role-negative-check:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-FUNCTIONAL
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh
    - ./stages/functional-testing-with-rest/teaming-check/teaming-change-role-negative-check.sh

## Topology check
topology-check:
  image: harshshekhar15/gitlab-job:v3
  stage: DIRECTOR-FUNCTIONAL
  dependencies:
    - client-components-check
  script:
    - chmod 755 ./stages/functional-testing-with-rest/topology-check/topology-check.sh
    - ./stages/functional-testing-with-rest/topology-check/topology-check.sh

## Selenium Grid Spin up
selenium-grid-deploy:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/director-gui/create-grid.sh
    - ./stages/director-gui/create-grid.sh

## Selenium tests
tcid-gaau01-gui-auth:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gaau01-gui-auth.sh
    - ./stages/director-gui/tcid-gaau01-gui-auth.sh

tcid-gacc01-gui-cluster:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gacc01-gui-cluster.sh
    - ./stages/director-gui/tcid-gacc01-gui-cluster.sh

tcid-gada01-gui-dashboard-home:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gada01-gui-dashboard-home.sh
    - ./stages/director-gui/tcid-gada01-gui-dashboard-home.sh

tcid-gato01-gui-dashboard-topology:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gato01-gui-dashboard-topology.sh
    - ./stages/director-gui/tcid-gato01-gui-dashboard-topology.sh

gui-dashboard:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/gui-dashboard.sh
    - ./stages/director-gui/gui-dashboard.sh

tcid-gaal01-gui-dashboard-alerts:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gaal01-gui-dashboard-alerts.sh
    - ./stages/director-gui/tcid-gaal01-gui-dashboard-alerts.sh

tcid-galo01-gui-dashboard-logs:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-galo01-gui-dashboard-logs.sh
    - ./stages/director-gui/tcid-galo01-gui-dashboard-logs.sh

tcid-gada02-gui-dashboard-overview:
  image: harshshekhar15/gitlab-job:v5
  stage: DIRECTOR-GUI
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/director-gui/tcid-gada02-gui-dashboard-overview.sh
    - ./stages/director-gui/tcid-gada02-gui-dashboard-overview.sh

## Selenium Grid Clean up
selenium-grid-cleanup:
  image: harshshekhar15/gitlab-job:v5
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - TCID-DIR-INSTALL-ON-LOCAL-HP
  script:
    - chmod 755 ./stages/cluster-tear-down/delete-grid.sh
    - ./stages/cluster-tear-down/delete-grid.sh

## E2E metrics stage
e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/e2e-metrics.sh
    - ./stages/cluster-tear-down/e2e-metrics.sh

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c1-cleanup.sh
    - ./stages/cluster-tear-down/c1-cleanup.sh

cluster2-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c2-cleanup.sh
    - ./stages/cluster-tear-down/c2-cleanup.sh

cluster3-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-TEAR-DOWN
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-tear-down/c3-cleanup.sh
    - ./stages/cluster-tear-down/c3-cleanup.sh
