#!/bin/bash
pod() {

echo "*************Litmus and Heapster Setup*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-install-and-upgrade/prerequisites/prerequisite-setup node '"'$GITHUB_USERNAME'"' '"'$GITHUB_PASSWORD'"''
}

node() {

echo "***Applying e2e-crd***********"
kubectl apply -f utils/e2e-crd.yml

GITHUB_USERNAME=$1
GITHUB_PASSWORD=$2

# Cloning oep-e2e repository which contains all the test scripts
git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/mayadata-io/oep-e2e.git

# Setup litmus on the cluster
kubectl apply -f oep-e2e/litmus/prerequisite/rbac.yaml
kubectl apply -f oep-e2e/litmus/prerequisite/crds.yaml

# creating docker secret
kubectl apply -f oep-e2e/litmus/prerequisite/docker-secret.yml -n litmus

## Installing heapster components on the cluster for node monitoring
git clone https://github.com/kubernetes-sigs/metrics-server.git

# Fix "no metrics known for node" error by adding - --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalDNS,ExternalIP,Hostname
sed -i -e '/args:/ a\          - --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalDNS,ExternalIP,Hostname \n          - --kubelet-insecure-tls' metrics-server/deploy/kubernetes/metrics-server-deployment.yaml
kubectl apply -f  metrics-server/deploy/kubernetes/
sleep 60

# The below line turns off case sensitive comparison of strings
shopt -s nocasematch

# Check if heapster is returning output
node_stats=$(kubectl top nodes 2>&1)
while [[ $node_stats == *error* ]]
do
    node_stats=$(kubectl top nodes 2>&1)
    echo "Waiting for heapster to return top node details"
    sleep 30
done

echo "*************Top Node Output*************"
kubectl top node

echo -e "\n*************Finished Prerequisites*************"

}

if [ "$1" == "node" ];then
  node $2 $3
else
  pod
fi