#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/chaos/cstor-App-pod-kill/app-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

export KUBECONFIG=~/.kube/cluster2_config

job_id=$(echo $1) #Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
pipeline_id=$(echo $2) # Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
commit_id=$(echo $3) #Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).
releaseTag=$(echo $4)
source ~/.profile
case_id=MCDE 

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
#Creating e2e custom resource result for the test.
bash utils/e2e-cr-new jobname:app-kill jobphase:Waiting
bash utils/e2e-cr-new jobname:app-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

test_name=$(bash utils/generate_test_name testcase=busybox-provision-app-kill metadata="")
echo $test_name

cd e2e-tests
echo "Running the litmus test for Busybox Deployment.."
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/deployers/run_litmus_test.yml busybox_app_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-kill                                         | 
 | Litmus job label  | label  | app: busybox-litmus                 | app: deploy-busybox-app-kill                     |
 | appLabel          | env    | app=busybox-sts                     | app=app-kill                                     | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-csi                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-appkill                               |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-csi/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: app-busybox-ns/value: app-kill/g' busybox_app_kill.yml
cat busybox_app_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.

bash ../utils/litmus_job_runner label='app:deploy-busybox-app-kill' job=busybox_app_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
# Update the e2e event for the job.
bash utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="app-kill";test_name=$(bash utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_app_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-kill                                         | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-app-kill              |
 | appLabel          | env    | app=busybox-sts                     | app=app-kill                                     | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-app-kill/g' busybox_loadgen_app_kill.yml

cat busybox_loadgen_app_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_app_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='liveness:busybox-liveness-app-kill' job=busybox_loadgen_app_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
# Update the e2e event for the job.
bash utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

################
# LitmusBook 3 #
################

# Performing Application Pod Chaos

test_name=$(bash utils/generate_test_name testcase=application-pod-failure metadata="")
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/chaos/app_pod_failure/run_litmus_test.yml appkill.yml

sed -i -e 's/app=jenkins-app/app=app-kill/g' \
-e 's/name: app-failure/name: app-kill/g' \
-e 's/value: app-jenkins-ns/value: app-kill/g' appkill.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' appkill.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: appkill
' appkill.yml

echo "Running the litmus test for Busybox Deployment application pod kill.."
cat appkill.yml

bash ../utils/litmus_job_runner label='name:application-pod-failure' job=appkill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
bash utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$?" != "0" ]; then
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-app-kill";test_name=$(bash utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_app_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-kill                                         | 
 | appLabel          | env    | app=busybox-sts                     | app=app-kill                                     |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-app-kill  |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-app-kill/g' busybox_loadgen_deprovision_app_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_app_kill.yml

cat busybox_loadgen_deprovision_app_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-app-kill' job=busybox_loadgen_deprovision_app_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
bash utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
exit 1;
fi

################
# LitmusBook 5 #
################

test_name=$(bash utils/generate_test_name testcase=busybox-deprovision-app-kill metadata="")
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/deployers/run_litmus_test.yml deprovision_app_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-kill                                         | 
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-app-kill                |
 | appLabel          | env    | app=busybox-sts                     | app=app-kill                                     | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-csi                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-appkill                               |
 | action            | env    | provision                           | deprovison                                       |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-app-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-csi/g' \
-e 's/value: app-busybox-ns/value: app-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_app_kill.yml

# Running the litmus test for Busybox Deprovision
cat deprovision_app_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='app:busybox-deprovision-app-kill' job=deprovision_app_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash utils/dump_cluster_state;
bash utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# Update result of the test case in github mayadata-io/e2e-konvoy repository.
if [ "$rc_val" != "0" ]; then
bash utils/e2e-cr-new jobname:app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash utils/e2e-cr-new jobname:app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
