#!/bin/bash


pod() {

echo -e "\n************************ Running GUI test ***********************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-gui/gui-dmaas-jiva-mysql node '"'$CI_PROJECT_NAME'"' '"'$CI_PIPELINE_ID'"' '"'$DOP_URL'"' '"'$GROUP'"' '"'$THREADS'"' '"'$AWS_CREDS'"' '"'$MINIO_CREDS'"''
}

node() {
path=$(pwd)
# Copy kubeconfig
export KUBECONFIG=~/.kube/config_c2

# ####################################
# ##  Sequencing and Running test   ##
# ####################################
bash utils/pooling jobname:tcid-dir-dmaas-cstor-non-restic
bash utils/e2e-cr jobname:tcid-dir-dmaas-mysql jobphase:Running


kubectl get ns

PV_CLAIM_NAME="mysql-pv-jiva-claim"
NAMESPACE="jiva-mysql"
STORAGE_CLASS_NAME="openebs-jiva-default"
NODE_PORT="32758"

kubectl create ns ${NAMESPACE}

mkdir -p $path/jiva-mysql
cp -R $path/stages/director-gui/template/mysql-manifest $path/jiva-mysql

# Add pv claim name, namespace and storage class name in mysql-pvc.yaml
sed 's|name: mysql-pv-claim|name: '${PV_CLAIM_NAME}'|' -i $path/jiva-mysql/mysql-manifest/mysql-pvc.yaml
sed 's|storageClassName: openebs-jiva-default|storageClassName: '${STORAGE_CLASS_NAME}'|' -i $path/jiva-mysql/mysql-manifest/mysql-pvc.yaml
sed 's|namespace: mysql-dmaas-jiva|namespace: '${NAMESPACE}'|' -i $path/jiva-mysql/mysql-manifest/mysql-pvc.yaml

cat $path/jiva-mysql/mysql-manifest/mysql-pvc.yaml

# Add pv claim name and namespace in mysql-official.yaml
sed 's|namespace: mysql-dmaas-jiva|namespace: '${NAMESPACE}'|' -i $path/jiva-mysql/mysql-manifest/mysql-official.yaml
sed 's|claimName: mysql-pv-claim|claimName: '${PV_CLAIM_NAME}'|' -i $path/jiva-mysql/mysql-manifest/mysql-official.yaml

cat $path/jiva-mysql/mysql-manifest/mysql-official.yaml

# Add node port and namespace in mysql-svc.yaml
sed 's|namespace: mysql-dmaas-jiva|namespace: '${NAMESPACE}'|' -i $path/jiva-mysql/mysql-manifest/mysql-svc.yaml
sed 's|nodePort: 32753|nodePort: '${NODE_PORT}'|' -i $path/jiva-mysql/mysql-manifest/mysql-svc.yaml

cat $path/jiva-mysql/mysql-manifest/mysql-svc.yaml


kubectl get ns
kubectl apply -f $path/jiva-mysql/mysql-manifest/
kubectl get pod -n ${NAMESPACE}

####################################
##   Prerequisites GUI Automation ##
####################################
URL=$3
echo -e "\nDOP URL: $URL\n"

CI_PROJECT_NAME=$(echo $1)
CI_PIPELINE_ID=$(echo $2)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}
GROUP=$(echo $4)
THREADS=$(echo $5)
AWS_CREDS=$(echo $6)
MINIO_CREDS=$(echo $7)


#make empty directory
mkdir -p selenium-auto
cd selenium-auto

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

# Copy credential file
cp ~/.dmaas/cred.ini cred.ini

bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} us-east-2
STATUS=$(echo $?)
cd ../..
bash $path/utils/e2e-cr jobname:tcid-dir-dmaas-mysql jobphase:Completed
if [ "$STATUS" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8
else
  pod
fi