#!/bin/bash


pod() {

## Running gui-dashboard test
echo -e "\n************************ Running GUI test ***********************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-gui/gui-dmaas-delete-minio node '"'$CI_PROJECT_NAME'"' '"'$CI_PIPELINE_ID'"' '"'$DOP_URL'"' '"'$GROUP'"' '"'$THREADS'"''
}

node() {
path=$(pwd)
# Copy kubeconfig
export KUBECONFIG=~/.kube/cluster2_config

####################################
##   Prerequisites GUI Automation ##
####################################

URL=$3
echo -e "\nDOP URL: $URL\n"

CI_PROJECT_NAME=$(echo $1)
CI_PIPELINE_ID=$(echo $2)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}
GROUP=$(echo $4)
THREADS=$(echo $5)

####################################
##  Sequencing and Running test   ##
####################################
bash utils/pooling jobname:tcid-dir-dmaas-schd-cstor-minio-bucket
bash utils/e2e-cr jobname:tcid-dir-dmaas-minio-delete jobphase:Running

#make empty directory
mkdir -p selenium-auto
cd selenium-auto

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} us-east-2
STATUS=$(echo $?)
cd ../..
bash utils/e2e-cr jobname:tcid-dir-dmaas-minio-delete jobphase:Completed
if [ "$STATUS" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi