#!/bin/bash

pod() {

## Running gui-dashboard test
echo -e "\n************************ Running GUI dashboard test ***********************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-gui/run-gui-tests node '"'$CI_PROJECT_NAME'"' '"'$CI_PIPELINE_ID'"' '"'$DOP_URL'"' '"'$GROUP'"' '"'$THREADS'"''
}

node() {

URL=$3
echo -e "\nDOP URL: $URL\n"

CI_PROJECT_NAME=$(echo $1)
CI_PIPELINE_ID=$(echo $2)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}
GROUP=$(echo $4)
THREADS=$(echo $5)

echo -e "\n************************ Run GUI tests **********************************\n"
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} us-east-2

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
