#!/bin/bash

pod() {

## Running "TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME"
echo -e "\n*************** Running TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME ****************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/openebs-install/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME node '"'$CI_JOB_ID'"' '"'$GITHUB_TOKEN'"' '"'$CI_COMMIT_REF_NAME'"''
}

node() {

path=$(pwd)

CI_JOB_ID=$1
GITHUB_TOKEN=$2
CI_COMMIT_REF_NAME=$3

job_id=$(echo $CI_JOB_ID)
gittoken=$(echo "$GITHUB_TOKEN")
current_time=$(date)
branch_name=$CI_COMMIT_REF_NAME
stage="OPENEBS-INSTALL"
test_desc="Verify deletion of CSPC with volume"
job_name=TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME

## E2E Test case plan link
e2e_tc_plan_link=https://e2e.mayadata.io/docs/director/openebs-provisioning/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME
echo -e "\nTC_E2E_PLAN_LINK: $e2e_tc_plan_link\n"

# Use cluster2 kube config
export KUBECONFIG=~/.kube/config_c2

bash utils/pooling jobname:tcid-dir-op-delete-spc-with-no-volume
bash utils/e2e-cr jobname:tcid-dir-op-delete-cspc-with-volume jobphase:Running

export KUBECONFIG=~/.kube/config_c3

kubectl create ns delete-cspc
kubectl apply -f $path/stages/openebs-install/template/cstor-sc.yml
kubectl get sc
sleep 15
kubectl get ns
kubectl apply -f $path/stages/openebs-install/template/minio-manifest/
sleep 60
kubectl get pod -n delete-cspc
sleep 60

kubectl create -f oep-e2e/litmus/director/TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME/run_litmus_test.yml
kubectl get pods -n litmus 

test_name=delete-cspc-with-volume

echo -e "\nTest Name: $test_name\n"
litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod

job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)

while [[ "$job_status" != "Completed" ]]
do 
  job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
  sleep 6
done

kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo -e "\nTest Result: $testResult\n"

echo -e "\nBranch: $branch_name\n"
if [[ $branch_name == "oep-release" ]]; then
  echo -e "\nUpdating $job_name test results\n"
  python3 oep-e2e/utils/result_update.py --job_id "$job_id" --stage "$stage" --test_desc "$test_desc" --test_result "$testResult" --time_stamp "$current_time" --token "$gittoken" --test_name "$test_name" --job_name "$job_name" --platform "konvoy"
fi

if [ "$testResult" != Pass ]
then
  export KUBECONFIG=~/.kube/config_c2 
  bash utils/e2e-cr jobname:tcid-dir-op-delete-cspc-with-volume jobphase:Completed
  exit 1;
else
  export KUBECONFIG=~/.kube/config_c2 
  bash utils/e2e-cr jobname:tcid-dir-op-delete-cspc-with-volume jobphase:Completed
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi