#!/bin/bash

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/functional/block-pool-creation-with-claimed-bd/block-pool-creation-with-claimed-bd node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

export KUBECONFIG=~/.kube/config_c2

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash utils/e2e-cr-new jobname:block-pool-creation-with-claimed-bd jobphase:Waiting
bash utils/e2e-cr-new jobname:block-pool-creation-with-claimed-bd jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

test_name=$(bash utils/generate_test_name testcase=block-pool-creation-with-claimed-bd metadata='')
echo $test_name

cd e2e-tests

cp experiments/functional/cspc-pool/block-pool-creation-with-claimed-bd/run_litmus_test.yml block-pool-creation-with-claimed-bd.yml

sed -i -e 's/value: cstor-cspc-disk-pool/value: cstor-cspc-disk-pool-claimed/g' block-pool-creation-with-claimed-bd.yml

cat block-pool-creation-with-claimed-bd.yml

bash ../utils/litmus_job_runner label='app:cstor-pool-creation-with-claimed-bd' job=block-pool-creation-with-claimed-bd.yml
cd ..
bash utils/dump_cluster_state;
bash utils/event_updater jobname:block-pool-creation-with-claimed-bd $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash utils/e2e-cr-new jobname:block-pool-creation-with-claimed-bd jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash utils/e2e-cr-new jobname:block-pool-creation-with-claimed-bd jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi