#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd oep-e2e-konvoy && bash stages/functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$ZFS_BRANCH'"' '"'$ZFS_DRIVER_IMAGE'"'

}

#######################################
#    Deploy ZFS LocalPV provisioner   #
#######################################

run_job() {

export KUBECONFIG=~/.kube/config_c2

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
zfs_branch=$(echo $4)
zfs_driver_image=$(echo $5)
releaseTag=$(echo $5 | cut -d ":" -f 2)
echo "releaseTag=$releaseTag"

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash utils/e2e-cr-new jobname:zfspv-provisioner jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-custom-topology jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-snapshot-clone jobphase:Waiting
bash utils/e2e-cr-new jobname:snap-clone-ext4 jobphase:Waiting
bash utils/e2e-cr-new jobname:snap-clone-xfs jobphase:Waiting
bash utils/e2e-cr-new jobname:zfs-vol-resize jobphase:Waiting
bash utils/e2e-cr-new jobname:zfs-vol-resize-ext4 jobphase:Waiting
bash utils/e2e-cr-new jobname:zfs-vol-resize-xfs jobphase:Waiting
bash utils/e2e-cr-new jobname:zv-property-modify jobphase:Waiting
bash utils/e2e-cr-new jobname:zv-property-modify-ext4 jobphase:Waiting
bash utils/e2e-cr-new jobname:zv-property-modify-xfs jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-shared-mount-volume-zfs jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-shared-mount-volume-ext4 jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-shared-mount-volume-xfs jobphase:Waiting
bash utils/e2e-cr-new jobname:zfspv-provisioner jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for deploying ZFS LocalPV provisioner
test_name=$(bash utils/generate_test_name testcase=zfspv-provisioner metadata="")
echo $test_name

# copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/zfs-localpv/zfs-localpv-provisioner/run_litmus_test.yml zfs_pv_provisioner.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc/g}' \
-e "/name: ZFS_BRANCH/{n;s/.*/            value: ${zfs_branch}/g}" \
-e "/name: ZFS_DRIVER_IMAGE/{n;s/.*/            value: ${zfs_driver_image}/g}" \
-e '/name: ZPOOL_CREATION/{n;s/.*/            value: "false"/g}' \
-e '/name: POOL_NAME/{n;s/.*/            value: zfs-test-pool/g}' \
-e '/name: POOL_TYPE/{n;s/.*/            value: striped/g}' \
-e '/name: ACTION/{n;s/.*/            value: provision/g}' \
-e '/name: COMPRESSION/{n;s/.*/            value: "on"/g}' \
-e '/name: DEDUP/{n;s/.*/            value: "on"/g}' \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/g}' \
-e '/name: VOLBLOCKSIZE/{n;s/.*/            value: 4k/g}' \
-e '/name: RECORDSIZE/{n;s/.*/            value: 4k/g}' zfs_pv_provisioner.yml

cat zfs_pv_provisioner.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../utils/litmus_job_runner label='name:openebs-zfspv-provision' job=zfs_pv_provisioner.yml
## Get the cluster state Once the litmus jobs completed.
cd ..
bash utils/dump_cluster_state;
## Update the e2e event for the job.
bash utils/event_updater jobname:zfspv-provisioner $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash utils/e2e-cr-new jobname:zfspv-provisioner jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5 $6
else
  connect_cluster
fi

