#!/bin/bash

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/functional/block-pool-deletion-with-volume/block-pool-deletion-with-volume node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

export KUBECONFIG=~/.kube/config_c2

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash utils/e2e-cr-new jobname:block-pool-deletion-with-volume-csi jobphase:Waiting
bash utils/e2e-cr-new jobname:block-pool-deletion-with-volume-csi jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

run_id="csi-volume";test_name=$(bash utils/generate_test_name testcase=busybox-provision-busybox-csi-volume metadata=${run_id})
echo $test_name

cd e2e-tests
echo "Running the litmus test for busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml deploy_csi_busybox_volume.yml

sed -i -e 's/value: app-busybox-ns/value: busybox-csi-volume/g' \
-e 's/app: busybox-litmus/app: busybox-litmus-csi-volume/g' \
-e 's/generateName: litmus-busybox-deploy-/generateName: litmus-busybox-csi-/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-csi/g' deploy_csi_busybox_volume.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_csi_busybox_volume.yml

cat deploy_csi_busybox_volume.yml

bash ../utils/litmus_job_runner label='app:busybox-litmus-csi-volume' job=deploy_csi_busybox_volume.yml
cd ..
bash utils/dump_cluster_state;
bash utils/event_updater jobname:block-pool-deletion-with-volume-csi $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

################
# LitmusBook 2 #
################

test_name=$(bash utils/generate_test_name testcase=block-cspc-pool-deletion-if-pool-with-volume metadata='')
echo $test_name

cd e2e-tests
cp experiments/functional/cspc-pool/block-pool-deletion-with-volume/run_litmus_test.yml csi-block-pool-deletion-with-volume.yml

sed -i -e "/name: APP_NAMESPACE/{n;s/.*/            value: busybox-csi-volume/g}" \
-e "/name: APP_LABEL/{n;s/.*/            value: 'app=busybox-sts'/g}" csi-block-pool-deletion-with-volume.yml

cat csi-block-pool-deletion-with-volume.yml

bash ../utils/litmus_job_runner label='app:pool-deletion-with-volume' job=csi-block-pool-deletion-with-volume.yml
cd ..
bash utils/dump_cluster_state;
bash utils/event_updater jobname:block-pool-deletion-with-volume-csi $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash utils/e2e-cr-new jobname:block-pool-deletion-with-volume-csi jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash utils/e2e-cr-new jobname:block-pool-deletion-with-volume-csi jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi