apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: mysql-dmaas-jiva
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
      nodePort: 32753
      protocol: TCP
  selector:
    app: wordpress
    tier: mysql
  sessionAffinity: None
  type: NodePort
