#!/bin/bash
pod() {

echo "*************Deploying Director On-Prem*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-health-check/maya-io-server-check node '"'$GITHUB_USERNAME'"' '"'$GITHUB_PASSWORD'"''
}

node() {

GITHUB_USERNAME=$1
GITHUB_PASSWORD=$2

URL=https://$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | head -n 1):30380
echo $URL

# Cloning oep-e2e repository which contains all the test scripts
git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/mayadata-io/oep-e2e.git
cd oep-e2e


######################
##   Running test  ##
######################
kubectl get po
kubectl create -f litmus/director/maya-io-server/run_litmus_test.yml

test_name=maya-io-server-check
echo $test_name

litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod

job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)

# Check completed status for job
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done

kubectl logs -f $litmus_pod -n litmus
kubectl get po

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult

if [ "$testResult" != Pass ]; then 
exit 1; 
fi

}

if [ "$1" == "node" ];then
  node $2 $3
else
  pod
fi
