#!/bin/bash
pod() {
  echo "*************maya-io-server check*************"
  sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-konvoy && bash stages/director-install-and-upgrade/director-health-check/components-health-check node '"'$GITHUB_USERNAME'"' '"'$GITHUB_PASSWORD'"''
}

node() {
  bash utils/pooling jobname:dop-deploy
  bash utils/e2e-cr jobname:components-health-check jobphase:Running

  GITHUB_USERNAME=$1
  GITHUB_PASSWORD=$2
  
  echo -e "********** Calling maya-io-server check **********"
  chmod 755 ./stages/director-install-and-upgrade/director-health-check/maya-io-server-check
  bash ./stages/director-install-and-upgrade/director-health-check/maya-io-server-check "$GITHUB_USERNAME" "$GITHUB_PASSWORD"  >maya-io-server-check.out 2>&1 &

  echo -e "\n********** Calling maya-ui check **********"
  chmod 755 ./stages/director-install-and-upgrade/director-health-check/maya-ui-check
  bash ./stages/director-install-and-upgrade/director-health-check/maya-ui-check "$GITHUB_USERNAME" "$GITHUB_PASSWORD" >maya-ui-check.out 2>&1 &
  
  tail -q -f maya-io-server-check.out --pid $!

  wait
  # Printing output
  # cat maya-io-server-check.out
  cat maya-ui-check.out
  rm -v maya-io-server-check.out maya-ui-check.out

  echo -e "\n********** Components health check finished **********!"

}

if [ "$1" == "node" ];then
  node $2 $3
else
  pod
fi