#!/bin/bash
set -ex

######################
##   Prerequisites  ##
######################
kubectl get po
URL=https://$(kubectl get node -o wide | awk {'print $6'} | head -n 4 | tail -n 1):30380
echo $URL
# Cloning oep-e2e repository which contains all the test scripts
# git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
# cd oep-e2e
######################
##   Running test  ##
######################
test_name=maya-ui-health-check
echo "Test name: $test_name"

kubectl get po

sed -i -e 's/generateName: app-check/generateName: maya-ui-health-check/g' \
-e 's/app: app-litmus/app: maya-ui-health-check-litmus/g' \
-e 's/value: test-name/value: maya-ui-health-check/g' \
-e 's/value: default /value: default/g' \
-e 's/value: pod-name/value: maya-ui/g' oep-e2e/litmus/director/common-checks/run_litmus_test.yml

cat oep-e2e/litmus/director/common-checks/run_litmus_test.yml

kubectl create -f oep-e2e/litmus/director/common-checks/run_litmus_test.yml

litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo "Litmus pod name: $litmus_pod"

job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done

kubectl logs -f $litmus_pod -n litmus
kubectl get po

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo "********** maya-ui check completed! **********"

if [ "$testResult" != Pass ]; then 
exit 1; 
fi
