apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cstor-storageclass
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "spc-volume"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi