kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-sc-gui
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  cstorPoolCluster: rec-create-test
  replicaCount: "1"
